---
- name: setup-tomcat
  hosts: all
  become: yes
  tasks:
  -   name: install java on RedHat
      yum:
        name: java
        state: installed
      when: ansible_os_family == "RedHat"
  -   name: install java on Debain
      apt:
        name: default-jdk
        state: present
      when: ansible_os_family == "Debain"
  -  name: download tomcat
     get_url:
        url: https://downloads.apache.org/tomcat/tomcat-9/v9.0.69/bin/apache-tomcat-9.0.69.tar.gz
        dest: /opt
  -  name: extract tomcat
     unarchive:
        src:  /opt/apache-tomcat-9.0.69.tar.gz
        dest: /opt
        remote_src: yes
  -  name: execute permissions
     file:
        path:  /opt/apache-tomcat-9.0.69/bin/startup.sh 
        mode:  0777  
  -  name:  start service
     shell:  nohup ./startup.sh
     args:
        chdir: /opt/apache-tomcat-9.0.69/bin

